name: 'Create Bucket - Terraform'
on:
  pull_request:
    branches:
      - "*"
jobs:
  terraform:
    name: 'Terraform'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v2
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: terraform init

      - name: Terraform Check
        uses: hashicorp/setup-terraform@v2
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: terraform plan -auto-approve

      - name: Terraform Apply
        uses: hashicorp/setup-terraform@v2
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: terraform apply -auto-approve
