name: 'Create Bucket - Terraform'
on:
  pull_request:
    branches:
      - "*"
jobs:
  setup_dependencies: 
    name: Config Terraform
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          args: '-var="aws_access_key=${{secrets.AWS_ACCESS_KEY_ID}}" 
                 -var="aws_secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}}"'

  create_bucket:
    name: Create Bucket
    needs: [setup_dependencies]
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Terraform Init
        run: terraform init

      - name: Terraform Check
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -input=true -var="${{ steps.extract_branch.outputs.branch }}"

      - name: Create bucket
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -input=false -var="${{ steps.extract_branch.outputs.branch }}"