name: 'Create Bucket - Terraform'
on:
  pull_request:
    branches:
      - "*"
jobs:
  terraform:
    name: 'Terraform'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          args: '-var="aws_access_key=${{secrets.AWS_ACCESS_KEY_ID}}", -var="aws_secret_key=${{secrets.AWS_SECRET_ACCESS_KEY}}"'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Check
        run: terraform plan -input=true

      - name: Terraform Apply
        run: terraform apply -input=true